# .swiftlint.yml
disabled_rules:
  - trailing_whitespace
  - line_length
  
opt_in_rules:
  - empty_count
  - empty_string
  
excluded:
  - Pods
  - .build
  - DerivedData
  - test2Tests
  - test2UITests
  
line_length:
  warning: 150
  error: 200
  
function_body_length:
  warning: 50
  error: 100
  
file_length:
  warning: 500
  error: 1000
  
type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    error: 2
  excluded:
    - id
    - i
    - j
    - x
    - y
    - url
